package com.example.flightbookingservice.dto;

import java.util.List;

import lombok.Data;

@Data
public class FlightSearchResponse {
    private Long flightId;
    private String originCity;
    private String destinationCity;
    private String airline;
    private int availableSeats;
    private int numberOfConnections;
    private double ticketPrice; // Original ticket price
    private double convertedPrice; // Converted ticket price

    // Driving details
    private String drivingFormattedTime;
    private double drivingDistance;
    private boolean drivingHasHighway;
    private boolean drivingHasCountryCross;

    // Images related to the destination city
    private List<FlickrImage> images;

    // Constructors, getters, and setters are generated by Lombok

    // Add an all-args constructor or use @AllArgsConstructor if needed
    // Consider adding a builder pattern with @Builder for more complex objects
}
